name: Terraform workflow
on:
  pull_request:
    paths:
      - 'terraform/modules/**'
      - '.github/workflows/terraform-workflow.yaml'
      - '.github/workflows/tfsec.yaml'

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/modules/eks-base

  docs:
    runs-on: ubuntu-latest
    needs: tfsec
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: terraform/modules/eks-base
          output-file: README.md
          output-method: inject
          git-push: "true"
